name: Atualizar Jogos Diários

on:
  schedule:
    - cron: '0 9,15,21 * * *' # Roda às 09h, 15h e 21h automaticamente
  workflow_dispatch: # Permite que você rode manualmente com um botão

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar código
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: |
          pip install playwright
          playwright install chromium

      - name: Rodar o Robô
        run: python scraper.py

- name: Commitar mudanças
        run: |
          git config --global user.name "Robo Bot"
          git config --global user.email "bot@github.com"
          git add jogos.json live.json  # Adicione o live.json aqui
          git commit -m "Atualizando jogos e live" || echo "Sem mudanças"
          git push
